---
title: "Fundamentals of Data Visualization"
output: html_notebook
author: "Marvin von Rappard"
---


```{r}
data(mtcars)
data(mpg)
library(ggplot2)
library(tidyverse)
library("ggpubr")
```

## Datasets

### mpg
```{r}
mpg
```

### mtcars
```{r}
mtcars
```


## LO1: Visualization basics, chart types

### Continuous variables

```{r}
ggplot(mpg, aes(displ, cty)) +
  geom_point() +
  labs(x = "Engine displacement (in litres)", y = "City miles per gallon (mpg)", title = "Comparison between engine displacement and miles per gallon")
```
#### Correlation between the variables

```{r}
cor(mpg$cty, mpg$displ, method="pearson")
```


```{r}
mtcars %>%
  ggplot(aes(qsec, mpg)) +
  geom_point() + 
  labs(x = "1/4 mile time", y = "Miles per gallon (mpg)", title = "1/4 mile time compared to miles per gallon (mpg)")
```

#### Correlation between the variables
```{r}
cor(mtcars$mpg, mtcars$qsec, method="pearson")
```

### Categorial Variables

```{r}
mpg_cyl <- mpg
mpg_cyl$cyl <- mpg_cyl$cyl %>% factor(levels = c(4, 5, 6, 8))

mpg_cyl %>%
  group_by(cyl) %>%
  summarize(avg_mpg = mean(cty)) %>%
  ggplot(aes(cyl, avg_mpg)) +
  geom_col() +
  labs(x = "Number of Cylinders", y = "Average city miles per gallon (mpg)", title = "Average Miles per gallon for each number of cylinders")
```

#### Correlation between the variables
```{r}
cor(mpg$cty, mpg$cyl, method="spearman")
```


```{r}
mtcars %>%
  group_by(gear) %>%
  summarize(avg_mpg = mean(mpg)) %>%
  ggplot(aes(x = gear, y = avg_mpg)) +
  geom_col() +
  labs(x = "Number of Gears", y = "Average miles per gallon (mpg)", title = "Average miles per gallon for each number of gears of a car")
```

#### Correlation between the variables
```{r}
cor(mtcars$mpg, mtcars$gear, method="spearman")
```


```{r}
mtcars_am <- mtcars
mtcars_am$am <- mtcars_am$am %>% factor(levels=c(0, 1), labels=c("Manual", "Automatic"))

mtcars_am %>%
  group_by(am) %>%
  summarize(avg_mpg = mean(mpg)) %>%
  ggplot(aes(am, avg_mpg)) +
  geom_col() + 
  labs(x = "Transmission type", y = "Average miles per gallon (mpg)", title = "Average miles per gallon by transmission type")
```

```{r}
mtcars_am %>%
  ggplot(aes(x = am, y = mpg)) + 
  geom_boxplot() +
  labs(x = "Transmission type", y = "Miles per gallon (mpg)", title = "Spread of miles per gallon by transmission type")
```

## LO2: Visual Perception

### Colors

```{r}
ggplot(mpg, aes(displ, cty, color=cyl)) +
  geom_point() +
  labs(x = "Engine displacement (in litres)", y = "City miles per gallon (mpg)", title = "Comparison between engine displacement and miles per gallon")
```

```{r}
ggplot(mpg_cyl, aes(displ, cty, color=cyl)) +
  geom_point() +
  scale_color_hue(l=40, c=35) +
  labs(x = "Engine displacement (in litres)", y = "City miles per gallon (mpg)", title = "Comparison between engine displacement and miles per gallon")
```

### Shapes
```{r}
mpg_manu <- mpg %>%
  group_by(manufacturer) %>%
  summarize(avg_mpg = mean(cty)) %>%
  arrange(avg_mpg) %>%
  slice(1:5)

pie(mpg_manu$avg_mpg, labels= mpg_manu$manufacturer, col=rainbow(length(mpg_manu$manufacturer)), main="Average city miles per gallon (mpg) per manufacturer")
```
```{r}
mpg_manu %>% ggplot(aes(manufacturer, avg_mpg, fill = manufacturer)) +
  geom_col() +
  labs(x = "Manufacturer", y = "Average city miles per gallon (mpg)", title = "Average city miles per gallon (mpg) per manufacturer")
```



### Scale

```{r}
ggplot(mpg, aes(displ, cty)) +
  geom_point() +
  scale_y_log10() +
  labs(x = "Engine displacement (in litres)", y = "City miles per gallon (mpg, log10)", title = "Comparison between engine displacement and miles per gallon")
```



